services:

  backend:
    build:
      context: ./almosafer-backend
      dockerfile: dockerfile
    container_name: reservation_backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      adminer:
        condition: service_started
      n8n:
        condition: service_started
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    ports:
      - '3000:3000'
    volumes:
      - ./.env:/app/.env:ro

  mysql:
    image: mysql:latest
    container_name: reservation_mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: reservation_adminer
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - '8081:8080'

  n8n:
    image: n8nio/n8n:latest
    container_name: reservation_n8n
    restart: unless-stopped
    ports:
      - '5678:5678'
    environment:
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
      TZ: ${GENERIC_TIMEZONE}
      N8N_PERSONALIZATION_ENABLED: false
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
      N8N_RUNNERS_ENABLED: true
      DB_SQLITE_POOL_SIZE: 5
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - mysql


volumes:
  mysql_data:
  n8n_data:
